### ISSUE TITLE
This website isn't made by you

### ISSUE THREAD

**Issue by grilledpython** [hktitof/my-website#6]
Its taken from BritannyChiang's GitHub

**Comment by hktitof** [comment]
first of all contacted Brittany, and showed her my portfolio she really liked it and surprised that i've built it from scratch with different technologies, you are probably new to the world of development, you can simply check my commits in my portfolio repo, the functionalities i added and many other things...etc, i already mentioned that the design is by Brittany Chiang, you guys are just talking without doing any efforts, if you wanna hear that its taken from BritannyChiang so you can be happy, YEAH , IT IS Hahahah

YOU GUYS ARE REALLY WEIRD, at least read my repo Description and check the commits and the structure, i agree with you the design is almost the same, but don't judge me because i don't have a design, it's like you are judging a guy who tried to rebuild same Facebook with same design but with different technologies, and he already mentioned it in the repo.

NEXT TIME I WILL JUST Reply with " READ Repo Description!!!!" you are just lucky i teached you this lesson :)
